config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'medicinas#index'
  resources :medicinas, only: [:index, :new, :create, :destroy] 
  resources :users, only: [:edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/medicina.rb
class Medicina < ApplicationRecord
  with_options format: { with: /\A[ぁ-んァ-ン一-龥]+\z/, message: '全角文字を使用してください' } do
  validates :medicina1
  validates :medicina2
  validates :medicina3
  validates :medicina4
  validates :medicina5
  validates :medicina6
  validates :medicina7
  validates :medicina8
  validates :medicina9
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == 'abc' && password == '1234'
    end
  end
end

app/controllers/medicinas_controller.rb
class MedicinasController < ApplicationController

  def index
    @medicinas = Medicina.all
  end

  def new
    @medicina= Medicina.new
  end
  
  def create
    @medicina = Medicina.create(medicina_params)
    if @medicina.save
      redirect_to root_path
    else
      render :new
    end
  end

  # def destroy
  #  @medicina = Medicina.destroy(medicina_params)
  # end
  # def show
  #   @medicina = Medicina.show(medicina_params)
  # end

  # def edit
  #   if user_signed_in? && current_user.id != @item.user_id
  #     redirect_to root_path
  #   end
  # end

  def medicina_params
    params.require(:medicina).permit(:medicina1, :medicina2, :medicina3, :medicina4, :medicina5, :medicina6, :medicina7, :medicina8, :medicina9 )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/medicinas_helper.rb
module MedicinasHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Medicine</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/medicinas/index.html.erb
<%# <%if @medicinas.present?%> 
<%= link_to current_user.name, edit_user_path(current_user) %>
<% @medicinas.each do |medicina| %>
<table border="1" id="medicinaTable">

  <tr>
    <th>利用者名</th>
    <td><%= medicina.medicina1 %></td>
    <th>薬の有無</th>
    <td><%= medicina.medicina2 %></td>
    <th>備考（薬の変更等）</th>
    <td><%= medicina.medicina3 %></td>
  </tr>

  <tr>
    <th>利用者名</th>
    <td><%= medicina.medicina4 %></td>
    <th>薬の有無</th>
    <td><%= medicina.medicina5 %></td>
    <th>備考（薬の変更等）</th>
    <td><%= medicina.medicina6 %></td>
  </tr>

  <tr>
    <th>利用者名</th>
    <td><%= medicina.medicina7 %></td>
    <th>薬の有無</th>
    <td><%= medicina.medicina8 %></td>
    <th>備考（薬の変更等）</th>
    <td><%= medicina.medicina9 %></td>
  </tr>
  <%# <% end %> 
</table>
<% end %>

<a href="/medicinas/new">
  <div class='purchase-btn'>
    <span class='purchase-btn-text'>入力する</span>
  </div>
</a>

<div class="more">
    <ul class="more_list">
      <li>
        <%= link_to '削除', medicina_path(medicina.id), method: :destroy %>
      </li>
    </ul>
</div>

app/views/medicinas/new.html.erb
<div >
  <%# <div class="container"> %>
    <%# <h3>入力する</h3> %>
    <%= form_with(model: @medicina, local: true) do |form| %>
      <%= form.text_field :medicina1, placeholder: "利用者名" %>
      <%= form.text_field :medicina2, placeholder: "薬の有無" %>
      <%= form.text_area :medicina3, placeholder: "備考", rows: "10" %>

      <%= form.text_field :medicina4, placeholder: "利用者名" %>
      <%= form.text_field :medicina5, placeholder: "薬の有無" %>
      <%= form.text_area :medicina6, placeholder: "備考", rows: "10" %>

      <%= form.text_field :medicina7, placeholder: "利用者名" %>
      <%= form.text_field :medicina8, placeholder: "薬の有無" %>
      <%= form.text_area :medicina9, placeholder: "備考", rows: "10" %>
      <%= form.submit "入力" %>
    <% end %>
  <%# </div> %>
</div>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'%>
      <%= link_to "チャットページに戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :name%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>